### ISSUE TITLE
Strain Gauge Data Sheet

### ISSUE THREAD

**Issue by DarioUrbina** [CatStrain/Cat_skin#10]
I don't think the Strain Gauge data sheet will be on Amazon, please find out which is the model of the SG and search for that data sheet somewhere else. You can let me know which is the model, I can try finding that data sheet.

You were talking about this issue in a README file. If it is something to be solved it is better to write issues like am doing. You can open an issue here and let me know the number so I can go and see it. 

README files are more informative.

__________________________________________________________________
I include here your original comment:
About the power problem, as I am running the test for our new strain gauges (120 ohms), I discover that 
while running the circuit and reading the signal output from single strain gauge, the overheating problem emerges. 
The strain gauges become more delicate and easy to break. For me, it seems that maybe the voltage is over the SG limitation, 
however, we can't acctually find the parameters on the Amazon page.

**Comment by JiaoranWang** [comment]
About that, I acrtually found a tutorial pdf about the voltage and circuit about the 120 ohm strain gauges. 
quote:
"Strain gauge signal conditioners typically provide a constant voltage source to power the bridge.
While there is no standard voltage level that is recognized industry wide, **excitation voltage levels of around 3 V and10 V are common.** 
**While a higher excitation voltage generates a proportionately higher output voltage, the higher voltage can also cause larger errors due to self-heating.** Again, it is very important that the excitation voltage be very accurate and stable. Alternatively, one can use a less accurate or stable voltage, and accurately measure, or sense, the
excitation voltage so the correct strain can be calculated."

**Comment by DarioUrbina** [comment]
Ok, please add the data sheet or information found into a folder in the Drive ("Data sheet or documentation" folder)
