### ISSUE TITLE
How to stop valero_receive_data_from_arduino MATLAB ?

### ISSUE THREAD

**Issue by DarioUrbina** [CatStrain/Cat_skin#8]
When running, the way I stop the recording is by just pausing the current execution, causing the program to go into a debugging mode, this could potentially be the reason of Issue #2 . 

Please include a way to terminate the program through the command window.

**Comment by TailunLiu** [comment]
That is the problem. This is because at the beginning of the program, it opens a serial port, and if you just stop in the middle and restart it, the port is not closed, therefore the program will give error. You have to wait until the program finishes, then you can run it the second time. If you stop it in the middle, the you have to reopen Matlab to run the code. There is a 'interval' parameter, which allows you to adjsut the loop length. Decreasing it will reduce the data collected by which reduce time. I will try to find a way to terminate the program, but for now please do not stop it when its running, otherwise you need to reboot Matlab.

**Comment by DarioUrbina** [comment]
I will try this. 
Descriptions including important information like this one need to come somewhere in the code or a README file. 
Thanks!

**Comment by DarioUrbina** [comment]
Based on our today's conversation,  you have found a way to terminate the program. Thanks.
